Red lib fixes
e2xlabs/redefined-name-resolver-js pull request #14
Opened 2023-02-21 08:04 UTC by Ivan-dev-RED

2023-02-27 19:18 UTC, Rednoll requested changes

2023-02-27 19:18 UTC, Rednoll commented on src/redefined.resolver.ts
> +        const targetAccountsWithoutEvm = resolvedAccounts.filter(it => (!networks || networks.includes(it.network) && it.network !== "evm"));
Default EVM logic can be moved to our resolvers from this global resolver

2023-02-27 19:18 UTC, Rednoll commented on src/redefined.resolver.ts
> +        const targetAccountsWithoutEvm = resolvedAccounts.filter(it => (!networks || networks.includes(it.network) && it.network !== "evm"));
It will be simpler and will no affect logic of ENS and Unst

2023-02-28 13:31 UTC, Ivan-dev-RED commented on src/services/resolvers/redefined-resolver.service.ts
> +    private async resolveEmail(domain: string): Promise<AccountRecord[]> {
ok

2023-02-28 13:31 UTC, Ivan-dev-RED commented on src/services/resolvers/redefined-resolver.service.ts
> +    private async resolveNickname(domain: string): Promise<AccountRecord[]> {
ok

2023-02-28 13:43 UTC, Ivan-dev-RED commented on src/services/resolvers/unstoppable-resolver.service.ts
>  const resolution = new Resolution();
ok

2023-02-28 13:43 UTC, Ivan-dev-RED commented on tests/moks/web3.ts
> +                    { addr: "0x123", network: "eth" },
ok

2023-02-28 17:22 UTC, Rednoll approved these changes

2023-02-28 18:05 UTC, Rednoll submitted a review, later dismissed

2023-03-01 09:37 UTC, Rednoll approved these changes

2023-03-01 09:39 UTC, merged